### ISSUE TITLE
Created distribution files (for scale to fit and adding back ?bin=) but don't know how to make it work with wasm version packages

### ISSUE THREAD

**Issue by joyrider3774** [aoneill01/wasm-gamebuino#10]
Hey,

I (re)created the distribution files for the WASM emulator version, unfortunatly i do not know how to get these files into the current emulators source code, as the files i change is normally part of the package and there is only one such script. So i had to duplicate and modify the files from the latest 0.70 unpkg package. It would be far better if there was a way to add these to your own github repo somehow. The problem with this system and my repo is that if the emulator gets updated i will need to update these files also in that repo i made…

You can see the files in my repo [here](https://github.com/joyrider3774/gamebuino_wasm_emulator_distribution) as well as the github pages deployed version [here](https://joyrider3774.github.io/gamebuino_wasm_emulator_distribution/) . For index1 & index2 html i based myself on your linked page ( http://games.aoneill.com/wasm-proto/ )

what did i actually do ?

* i[ndex.html / js](https://joyrider3774.github.io/gamebuino_wasm_emulator_distribution/index.html) is basically the default emulator setup based on your page [here](http://games.aoneill.com/wasm-proto/)
* [index2.html / js](https://joyrider3774.github.io/gamebuino_wasm_emulator_distribution/index2.html) is a copy of index.html but using the other console skin i used before
* [console-fullscreen.html / js](https://joyrider3774.github.io/gamebuino_wasm_emulator_distribution/console-fullscreen.html) is the console screen from index.html but with resizing to fit the browser window
* [console2-fullscreen.html / js](https://joyrider3774.github.io/gamebuino_wasm_emulator_distribution/console2-fullscreen.html) is the console screen from index2.html (using the new skin) but with resizing to fit the browser window
* [emulator-fullscreen.html / js](https://joyrider3774.github.io/gamebuino_wasm_emulator_distribution/emulator-fullscreen.html) is just the screen scaled to fit the window. There are no touch screen controls to press and you can't use the mouse.
* In all files i added the `?bin=` parameter option again, it was not present in the package version as far as i could tell as you supplied the file normally using src attribute of the emulator. 

examples:
- `https://joyrider3774.github.io/gamebuino_wasm_emulator_distribution/emulator-fullscreen.html?bin=https://raw.githubusercontent.com/Rodot/Games-META/master/binaries/METAtris/METAtris.bin`
- `https://joyrider3774.github.io/gamebuino_wasm_emulator_distribution/console2-fullscreen.html?bin=https://raw.githubusercontent.com/Rodot/Games-META/master/binaries/METAtris/METAtris.bin`
-  ` https://joyrider3774.github.io/gamebuino_wasm_emulator_distribution/index2.html?bin=https://raw.githubusercontent.com/Rodot/Games-META/master/binaries/METAtris/METAtris.bin`

Maybe you can somehow find a way to host these yourself or maybe you can create a new distrubtion repo on your github and host it with github pages. Perhaps there is even a way to make a github action on Push / Merge request merges that will update the distribution repo or so. People could then link to the files on the github pages host and use `?bin=` with any of those files above to make links to their game bin files (perhaps also hosted on github)

**Comment by aoneill01** [comment]
I'll try to find some time this weekend to investigate this. Just off the top of my head I'm wondering if I can update the `GamebuinoEmulator` web component to have attributes for the background image and fullscreen so that there can be a single js file with multiple html files.

**Comment by aoneill01** [comment]
@joyrider3774 - Here is what I have so far on a `feature/background-and-fullscreen` branch. (I have Github Pages pointed at this branch for now.) There are attributes on `<gamebuino-emulator />` for `background` (1, 2, or none) and `fullscreen`.

- Added style picker to index.html: [example](https://aoneill01.github.io/wasm-gamebuino/)
- Added a fullscreen.html that has url params for `bin` and `background`: [no console example](https://aoneill01.github.io/wasm-gamebuino/fullscreen.html?bin=https://raw.githubusercontent.com/aoneill01/meta-dn2/feature/no-sd/binaries/DnGame/DNGAME.BIN), [original console example](https://aoneill01.github.io/wasm-gamebuino/fullscreen.html?bin=https://raw.githubusercontent.com/Rodot/Games-META/master/binaries/DefendPluto/DefendPluto.bin&background=1), [new console example](https://aoneill01.github.io/wasm-gamebuino/fullscreen.html?bin=https://raw.githubusercontent.com/Rodot/Games-META/master/binaries/CatsAndCoinsDemo/CatsAndCoinsDemo.bin&background=2)

What do you think? Anything not working or missing for you?

**Comment by joyrider3774** [comment]
Hi @aoneill01,

Very nice, All options seem to be present and seem to be working correctly as far as i can tell, except fullscreen.html needs a `overflow: hidden;` on the body style. If you resize your window to a very small size (smaller than original background size) scrollbars would appear and you can go around that by setting overflow to hidden. Except for that everything seems to be working perfectly as far as i can tell.

Thank you very much for implementing this already this is a big improvement and will help for people adding their games to itch.io etc
