### ISSUE TITLE
Release sound support to npm

### ISSUE THREAD

**Issue by erwinbonsma** [aoneill01/wasm-gamebuino#5]
I was pleasantly surprised to see sound working when I used the emulator at http://games.aoneill.com/wasm-proto/

However, as far as I can see, this was added after 0.5.0 which is the latest version available on npm.

Is there a technical reason why sound support has not yet been released? If not, can you release a new version which includes this? Having sound really adds to the experience of playing games via the emulator. Thanks!

**Comment by aoneill01** [comment]
@erwinbonsma - I just published version 0.6.0 which should include the most recent changes, including sound.

**Comment by erwinbonsma** [comment]
Excellent! Thanks for quickly picking this up. Nice to have sound with my new creation when hosted on my own website. It would be nice if it also finds its way to the gamebuino website. Is that actually already using this WASM-based emulator, or still the old one?

**Comment by aoneill01** [comment]
Yes, it would be nice to have on the Gamebuino website. It looks like the site is still using the Javascript-based version.
